### ISSUE TITLE
Could not find: islands.ive

### ISSUE THREAD

**Issue by onox** [kbale/osgocean#45]
I get `Could not find: islands.ive` even though the file really exists in `%install_path%/bin/resources/island/` as the usage instructions say.

**Comment by kbale** [comment]
Are you able to load ive models normally with osg?

**Comment by onox** [comment]
I don't know. Normally I use OSG via FlightGear, and its data repository doesn't have any ive models.

**Comment by kbale** [comment]
It might be worth testing whether or not the model can be viewed with osg's
own viewer exe on the command line e.g. "osgviewer islands.ive"

Could you verify this for me?

**Comment by onox** [comment]
I can view the model with osgviewer.

**Comment by hbaqueiro** [comment]
I am facing the same problem
```
osgOcean 1.0.1

Building scene... 
  . Loading cubemaps: 0.000714s
  . Generating ocean surface: 3.7e-05s
  . Creating ocean scene: 0.000245s
Could not find: islands.ive
0.001865s
  . Loading islands:   . Setting up lighting: 2.2e-05s
complete.
Time Taken: 0.002915s
```
even though there is a islands.ive: /osgocean/resources/island/islands.ive
Any suggestions?

**Comment by as14g18** [comment]
Any update on this?
