### ISSUE TITLE
License of files in osgOcean-Resources-1.0.1.rar

### ISSUE THREAD

**Issue by onox** [kbale/osgocean#46]
What is the license of these files? LGPLv2?

And why are they not part of the repository?

**Comment by aluaces** [comment]
I am also interested in this issue, given that it directly affects redistribution procedures.

**Comment by romainreignier** [comment]
Does someone know if the Ressources files are still hosted somewhere on the web?
Thanks.

**Comment by kbale** [comment]
I'll see if I have a copy of them still kicking about tonight.

They're just for the demo program though really.

**Comment by romainreignier** [comment]
@kbale Ok, thank you.

>  They're just for the demo program though really.

I know, but because I am not sure if osgocean works well with latest versions of OpenSceneGraph, I would like to see if the demo is working correctly.

**Comment by romainreignier** [comment]
@kbale Did you find the files for the demo?
Thanks

**Comment by kbale** [comment]
Hi Romain,

I've added all the missing resource files, although I haven't checked them
thoroughly so if there's anything missing let me know.

They're in the /demo folder.

Hope that helps.

**Comment by romainreignier** [comment]
Hi @kbale,

Thanks a lot, the demo is now working!

But I had to modify de demo [CMakeLists.txt](https://github.com/kbale/osgocean/blob/9bca61e32163445e26bf4170326292a627a24edf/src/oceanExample/CMakeLists.txt#L5) to point to the correct path for the resources. Do you want me to create a Pull Request or you will make the changes?

Note that the `boat` for the `--testCollision` flag is missing.

I was able to see the demo properly with OSG **3.2.2** but not with a recent 3.4/3.5 version (graphic glitches/artifacts), even with the several patches I could find on the other issues ([here](https://github.com/kbale/osgocean/issues/47)) or forks ([here](https://github.com/repagh/osgocean/tree/01148e85a77522a882a8affa32df25c8ddc424ec)) of this project.

For now, I am OK to be stuck at OSG 3.2.2 but do you have an idea why it is now broken with recent releases of OSG and do you have plan to patch it?

**Comment by kbale** [comment]
Hi Romain,

Do you want me to create a Pull Request or you will make the changes?


That would be very helpful thank you.

Note that the boat for the --testCollision flag is missing.


Thanks for the tip, I'll have a route around and see if I can find it again.

>
> For now, I am OK to be stuck at OSG 3.2.2 but do you have an idea why it
> is now broken with recent releases of OSG and do you have plan to patch it?


I'm afraid I stopped using OSG regularly a while back when I started
working for a company that used it's own custom scenegraph so I'm a bit out
of touch with the recent changes. I do hope to patch it up and also improve
performance at some point but I can't tell you exactly when and it probably
won't be for a while I'm afraid.

Nice to know it's still used by people, thanks :)

Kim.

**Comment by fcami** [comment]
Hi Romain, Kim,

The Internet Archive has the Resources RAR archived: https://web.archive.org/web/20160807181456/http://osgocean.googlecode.com/files/osgOcean-Resources-1.0.rar

I've also submitted a PR:
https://github.com/kbale/osgocean/pull/52
that makes osgOcean work with OSG 3.4+.
Romain, could you test and report?

@Kim thanks a bunch, osgOcean is very cool.

Cheers
François

**Comment by romainreignier** [comment]
Hi @fcami ,

I have seen your PR, I will try to test it.

I had already tried to update osgOcean for OSG>3.4 but with no success.

And thanks for the tip about the resources files, I have saved them!

**Comment by fcami** [comment]
Hi @romainreignier 

Were you able to test my PR?

**Comment by romainreignier** [comment]
Sorry, I forgot to came back to you. I have now answered in issue #52
