### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by Krosyus** [kbale/osgocean#55]
Hello i'm new in osgOcean and i want to ask you, if you have a documentation please ??
Thank you in advance ^^

**Comment by kbale** [comment]
Hi Souffou,

I'm afraid there isn't any documentation. The sample app should help you
get started though.

Hope that helps,

Kim.

**Comment by Krosyus** [comment]
Oh T-T
Thank you for your answer. 
I would manage then. 
Have a good day
